# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to npm (CI)

on:
  push:
    branches:
      - master
    paths: 
      - packages/react-keycloak-id/**
      - .github/workflows/publish.yml

jobs:
  
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    
    steps: 
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Publish package
      run: |-
        cd packages/react-keycloak-id && npm i semantic-release@20.0.2 && npm run semantic-release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
